/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.gustavo.trabajotitulacion.ui;

import com.gustavo.trabajotitulacion.controllers.ProveedorController;
import com.gustavo.trabajotitulacion.objects.Proveedor;
import com.gustavo.trabajotitulacion.utils.ClienteConfirmadaListener;
import com.gustavo.trabajotitulacion.utils.ClienteConfirmadoEvent;
import com.gustavo.trabajotitulacion.utils.ProveedorConfirmadaListener;
import com.gustavo.trabajotitulacion.utils.ProveedorConfirmadoEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class IntFrProveedor extends javax.swing.JInternalFrame {

    private boolean paraGuardar = false;

    private ProveedorController proveedorController;

    private List<ProveedorConfirmadaListener> listeners = new ArrayList<>();

    public void agregarProveedorConfirmadaListener(ProveedorConfirmadaListener listener) {
        listeners.add(listener);
    }

    private void notificarProveedorConfirmada() {
        ProveedorConfirmadoEvent event = new ProveedorConfirmadoEvent(this);
        for (ProveedorConfirmadaListener listener : listeners) {
            listener.proveedorConfirmada(event);
        }

    }

    /**
     * Creates new form IntFrProveedor
     */
    public IntFrProveedor() {
        initComponents();
        llenarTabla();
    }

    public void llenarTabla() {
        try {
            proveedorController = new ProveedorController();
            List<Proveedor> listadoProveedores = proveedorController.getAllObjects();
            grillaProveedores1.setProveedores(listadoProveedores);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IntFrProveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IntFrProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void habilitarBotones(boolean btnNuevo, boolean btnEditar, boolean btnCancelar, boolean btnGuardar) {
        this.btnNuevo.setEnabled(btnNuevo);
        this.btnEditar.setEnabled(btnEditar);
        this.btnCancelar.setEnabled(btnCancelar);
        this.btnGuardar.setEnabled(btnGuardar);
    }

    public void habilitarTextBox(boolean estaHabilitado) {
        txtNombre.setEnabled(estaHabilitado);
        txtEmail.setEnabled(estaHabilitado);
        txtTelefono.setEnabled(estaHabilitado);
        txtDireccion.setEnabled(estaHabilitado);
    }

    public void limpiarTextBox() {
        txtNombre.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grillaProveedores1 = new com.gustavo.trabajotitulacion.ui.grillas.GrillaProveedores();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProveedores = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblTipoOperacion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        cbOpcionesBusqueda = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proveedores");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camion-de-reparto.png"))); // NOI18N
        jLabel1.setText("Gestión de proveedores");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Email:");

        txtNombre.setEnabled(false);

        txtTelefono.setEnabled(false);

        txtEmail.setEnabled(false);

        txtDireccion.setEnabled(false);

        tbProveedores.setModel(grillaProveedores1);
        tbProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProveedores);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/agregar-contacto.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lapices.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boton-x.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disco-flexible.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Filtrar proveedores");

        cbOpcionesBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por nombre", "Por email", "Por telefono" }));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-encuentra-hombre-usuario-32.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtEmail)
                                    .addComponent(txtDireccion)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(txtBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbOpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnNuevo)
                            .addComponent(btnCancelar))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbOpcionesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        paraGuardar = true;
        limpiarTextBox();
        habilitarTextBox(true);
        habilitarBotones(false, false, true, true);
        lblTipoOperacion.setText("Operacion: agregar proveedor");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tbProveedores.getSelectedRow();
        boolean estanVacios = txtDireccion.getText().equals("") && txtEmail.getText().equals("") && txtTelefono.getText().equals("") && txtNombre.getText().equals("");

        if (filaSeleccionada >= 0 && !estanVacios) {
            paraGuardar = false;
            habilitarTextBox(true);
            habilitarBotones(false, false, true, true);
            lblTipoOperacion.setText("Operacion: modificar proveedor");
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para editar.", "Informacion", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        paraGuardar = false;
        limpiarTextBox();
        habilitarTextBox(false);
        habilitarBotones(true, true, false, false);
        lblTipoOperacion.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            // TODO add your handling code here:
            boolean estanVacios = txtDireccion.getText().trim().equals("") && txtEmail.getText().trim().equals("") && txtTelefono.getText().trim().equals("") && txtNombre.getText().trim().equals("");

            proveedorController = new ProveedorController();

            int filaSeleccionada = tbProveedores.getSelectedRow();

            if (paraGuardar) {
                if (!estanVacios) {
                    Proveedor proveedorNuevo = new Proveedor();
                    proveedorNuevo.setDireccion(txtDireccion.getText().trim());
                    proveedorNuevo.setEmail(txtEmail.getText().trim());
                    proveedorNuevo.setNombre(txtNombre.getText().trim());
                    proveedorNuevo.setTelefono(txtTelefono.getText().trim());

                    proveedorController.insertObject(proveedorNuevo);
                    llenarTabla();
                    habilitarTextBox(false);
                    habilitarBotones(true, true, false, false);
                    limpiarTextBox();
                    lblTipoOperacion.setText("");
                    notificarProveedorConfirmada();
                } else {
                    JOptionPane.showMessageDialog(null, "Complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                if (!estanVacios) {
                    if (filaSeleccionada >= 0) {
                        Proveedor clienteEditar = grillaProveedores1.getProveedor(filaSeleccionada);
                        clienteEditar.setDireccion(txtDireccion.getText().trim());
                        clienteEditar.setEmail(txtEmail.getText().trim());
                        clienteEditar.setNombre(txtNombre.getText().trim());
                        clienteEditar.setTelefono(txtTelefono.getText().trim());

                        boolean resultado = proveedorController.modifiedObject(clienteEditar);
                        System.out.println("resultado = " + resultado);
                        llenarTabla();
                        habilitarTextBox(false);
                        habilitarBotones(true, true, false, false);
                        limpiarTextBox();
                        lblTipoOperacion.setText("");
                        notificarProveedorConfirmada();

                    } else {
                        JOptionPane.showMessageDialog(null, "Seleccione un proveedor.", "Advertencia", JOptionPane.WARNING_MESSAGE);

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IntFrProveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IntFrProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tbProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProveedoresMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tbProveedores.getSelectedRow();

        if (filaSeleccionada >= 0) {
            Proveedor proveedorSeleccionado = grillaProveedores1.getProveedor(filaSeleccionada);
            txtNombre.setText(proveedorSeleccionado.getNombre().trim());
            txtEmail.setText(proveedorSeleccionado.getEmail().trim());
            txtDireccion.setText(proveedorSeleccionado.getDireccion().trim());
            txtTelefono.setText(proveedorSeleccionado.getTelefono().trim());

        }
    }//GEN-LAST:event_tbProveedoresMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // TODO add your handling code here:
            String itemSeleccionado = ((String) cbOpcionesBusqueda.getSelectedItem()).trim();
            proveedorController = new ProveedorController();
            List<Proveedor> listadoProveedores;

            switch (itemSeleccionado) {
                case "Por nombre":
                    listadoProveedores = proveedorController.getAllObjectsByName(txtBuscar.getText().trim());
                    grillaProveedores1.setProveedores(listadoProveedores);
                    break;
                case "Por telefono":
                    listadoProveedores = proveedorController.getAllObjectsByPhone(txtBuscar.getText().trim());
                    grillaProveedores1.setProveedores(listadoProveedores);
                    break;
                case "Por email":
                    listadoProveedores = proveedorController.getAllObjectsByEmail(txtBuscar.getText().trim());
                    grillaProveedores1.setProveedores(listadoProveedores);
                    break;
                default:
                    throw new AssertionError();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IntFrProveedor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IntFrProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbOpcionesBusqueda;
    private com.gustavo.trabajotitulacion.ui.grillas.GrillaProveedores grillaProveedores1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipoOperacion;
    private javax.swing.JTable tbProveedores;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
